Kocal/vue-web-extension

- template/package.json
> Rename command « build:env » to « build:dev »

- template/package.json
> Add command « watch:dev »

- template/src/popup/router/routes.js
> Routes: replace « require » by « import »

- .travis.yml
- tests/test_axios.sh
- tests/test_router.sh
- tests/test_store.sh
- tests/test_version.sh
> Refacto Travis output 

- template/webpack.config.js
> feat: allow unsafe-eval for Chrome CSP, in development mode only

- template/package.json
- template/webpack.config.js
> feat: update vue-loader to v15

- .travis.yml
> chore(ci): configure cache for yarn and node_modules

- meta.js
- template/.eslintrc.js
- template/package.json
- template/src/background.js
- template/src/popup/App.vue
- template/src/popup/popup.js
- template/src/popup/router/index.js
- template/src/popup/router/pages/Index.vue
- template/src/popup/router/routes.js
- template/src/store/actions.js
- template/src/store/getters.js
- template/src/store/index.js
- template/src/store/mutation-types.js
- template/src/store/mutations.js
- tests/generate_extension.exp
> feat: add eslint support

- README.md
- meta.js
- template/.eslintrc.js
- template/.prettierc
- template/package.json
- tests/generate_extension.exp
> feat: add prettier

- template/.babelrc
> feat(babel): specify browser list

- template/.babelrc
- template/package.json
> feat(babel): add optional chaining plugin

- .travis.yml
- tests/test_axios.sh
> fix(tests): handle external scripts errors properly

- .travis.yml
- README.md
- meta.js
- scenarios/full-airbnb.json
- scenarios/full.json
- scenarios/minimal.json
- utils/index.js
It:
- sort dependencies
- install dependencies
Again, thanks to https://github.com/vuejs-templates/webpack :smile:
> feat: add auto-install behavior

- meta.js
- utils/index.js
> feat(auto-install): run Prettier

- template/package.json
Related dependabot PR: #93, #99, #100.
> chore(deps): update babel-loader

- template/package.json
Related dependabot PR: #106 #107 #108
> chore(deps): update webpack

- template/package.json
Related dependabot PR: #89 #90 and #92
> chore(deps): update sass-loader

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> community: add issues template, and PR template

- template/package.json
> chore(deps): update webpack to 4.8.3

- template/package.json
> chore(deps): update cross-env to 5.1.5

- template/package.json
> chore(deps): update vue-loader to 15.1.0

- template/package.json
> chore(deps): update eslint-import-resolver-webpack to 0.10.0

- template/package.json
> chore(deps): update babel-loader to 8.0.0-beta.3

- template/package.json
- `core`: #126, #129 and #132.
- `preset-env`: #125, #127 and #130.
- `plugin-proposal-optional-chaining`: #124, #128 and #131.
> chore(deps): update babel to 7.0.0-beta.47

- template/package.json
- https://github.com/Kocal/vue-web-extension/pull/162
- https://github.com/Kocal/vue-web-extension/pull/165
- https://github.com/Kocal/vue-web-extension/pull/166
> chore(deps): update cross-env to 5.1.6

- template/package.json
- https://github.com/Kocal/vue-web-extension/pull/163
- https://github.com/Kocal/vue-web-extension/pull/168 
- https://github.com/Kocal/vue-web-extension/pull/169
> chore(deps): update vue-loader to 15.2.0

- template/package.json
> chore(deps): update webpack-cli to 2.1.4

- template/package.json
- https://github.com/Kocal/vue-web-extension/pull/210
- https://github.com/Kocal/vue-web-extension/pull/213
> chore(deps): update prettier to ^1.13.5

- template/package.json
- https://github.com/Kocal/vue-web-extension/pull/211
- https://github.com/Kocal/vue-web-extension/pull/212
- https://github.com/Kocal/vue-web-extension/pull/214
> chore(deps): update webpack to ^4.12.0

- examples/full-airbnb/.babelrc
- examples/full/.babelrc
- examples/minimal/.babelrc
- template/.babelrc
| New feature?  | no
| Fixed tickets | #...   
I don't know how #57 tests passed.
> fix: .babelrc format

- README.md
- meta.js
- scenarios/full-airbnb.json
- scenarios/full.json
- template/package.json
| Tests pass?   | -      
| Fixed tickets | #219   
The user can choose between pretty-quick or precise-commits.
> feat: setup git precommit hook for running Prettier

- meta.js
- template/package.json
| New feature?  | no
| Fixed tickets | #250    
I really did shit on this feature.
> fix: prettier git hook is not asked during init

- template/package.json
| Fixed tickets | #256    
Better auto-completion on `chrome.*` :tada:
> feat(deps): add @types/chrome

- .travis.yml
- meta.js
- scenarios/full-airbnb.json
- scenarios/full.json
- scenarios/minimal.json
- template/scripts/remove-evals.js
- template/src/manifest.json
- template/src/options/App.vue
- template/src/options/options.html
- template/src/options/options.js
- template/webpack.config.js
- tests/test_options.sh
| Fixed tickets | #...   
This feature add a prompt than will generate a simple options page.
https://developer.chrome.com/extensions/options
> feat: add prompt for options page

- .travis.yml
Use [`yarn install --frozen-lockfile`](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile) to install dependencies
> chore(ci): some tweaks

- README.md
> chore(readme): add AppVeyor badge

- meta.js
| New feature?  | no
| Fixed tickets | #284
> chore: remove double quotes from "meta.js"

- .appveyor.yml
- .travis.yml
- meta.js
- scenarios/full-airbnb.json
- scenarios/full.json
- scenarios/minimal.json
- template/package.json
- template/src/background.js
- template/src/options/options.js
- template/src/popup/popup.js
- tests/test_web_extension_polyfill.ps1
- tests/test_web_extension_polyfill.sh
> chore(prompt): add prompt for Mozilla Polyfill

- examples/full-airbnb/package.json
- examples/full-airbnb/scripts/build-zip.js
- examples/full-airbnb/yarn.lock
- examples/full/package.json
- examples/full/scripts/build-zip.js
- examples/full/yarn.lock
- examples/minimal/package.json
- examples/minimal/scripts/build-zip.js
- examples/minimal/yarn.lock
- template/package.json
- template/scripts/build-zip.js
| New feature?  | no
| Fixed tickets | #338
> fix: remove vulnerable "zip-folder" package for "archiver"

- template/package.json
> feat: install babel runtime

- examples/full-airbnb/package.json
- examples/full-airbnb/yarn.lock
- examples/full/package.json
- examples/full/yarn.lock
- examples/minimal/package.json
- examples/minimal/yarn.lock
- generate-examples.sh
- package.json
- template/package.json
- yarn.lock
Update some dependencies, also fix some security issues.
> chore: update dependencies and try to fix security issues

- template/package.json
- template/webpack.config.js
| Fixed tickets | #426   
Also configure the `manifest` key.
> feat(hot-reload): migrate to webpack-extension-reloader

- .github/FUNDING.yml
> chore: add funding button

- .appveyor.yml
- .travis.yml
- README.md
- template/package.json
- template/webpack.config.js
BREAKING CHANGE: Update Node.js miminum version from 8 to 10.
> BC/chore: Update minimum Node.js version from 8 to 10, update webpack deps
